name: UI Tests

on:
  push:
    branches:
      - master
      - dev-*
      - release-*
  pull_request:
    branches:
      - master
      - dev-*
      - release-*

jobs:
  WebSignIn:
    name: Web Sign In / Single Sign On (iOS)
    runs-on: macos-12
    steps:
    - uses: actions/checkout@master
    - uses: ./.github/actions/setup-secrets
      with:
        okta_plist: "${{ secrets.TEST_OKTA_PLIST }}"
        test_configuration: "${{ secrets.TEST_CONFIGURATION }}"
    - name: Check stuff out
      run: cat Samples/Shared/TestConfiguration.xcconfig |base64
    - name: Test Web Sign In
      run: |
        xcodebuild \
            -derivedDataPath Build/DerivedData \
            -clonedSourcePackagesDirPath Build/ClonedSources \
            -workspace OktaMobileSDK.xcworkspace \
            -scheme "WebSignIn (iOS)" \
            -destination 'platform=iOS Simulator,name=iPhone 12,OS=15.4' \
            test
    - name: Test Single Sign In
      run: |
        xcodebuild \
            -derivedDataPath Build/DerivedData \
            -clonedSourcePackagesDirPath Build/ClonedSources \
            -workspace OktaMobileSDK.xcworkspace \
            -scheme "SingleSignOn (iOS)" \
            -destination 'platform=iOS Simulator,name=iPhone 12,OS=15.4' \
            test

  DeviceAuthSignIniOS:
    name: Device Auth Sign In (iOS)
    runs-on: macos-12
    steps:
    - uses: actions/checkout@master
    - uses: ./.github/actions/setup-secrets
      with:
        okta_plist: "${{ secrets.TEST_OKTA_PLIST }}"
        test_configuration: "${{ secrets.TEST_CONFIGURATION }}"
    - name: Test
      run: |
        xcodebuild \
            -derivedDataPath Build/DerivedData \
            -clonedSourcePackagesDirPath Build/ClonedSources \
            -workspace OktaMobileSDK.xcworkspace \
            -scheme "DeviceAuthSignIn (iOS)" \
            -destination 'platform=iOS Simulator,name=iPhone 12,OS=15.4' \
            test

  DeviceAuthSignIntvOS:
    name: Device Auth Sign In (tvOS)
    runs-on: macos-12
    steps:
    - uses: actions/checkout@master
    - uses: ./.github/actions/setup-secrets
      with:
        okta_plist: "${{ secrets.TEST_OKTA_PLIST }}"
        test_configuration: "${{ secrets.TEST_CONFIGURATION }}"
    - name: Test
      run: |
        xcodebuild \
            -derivedDataPath Build/DerivedData \
            -clonedSourcePackagesDirPath Build/ClonedSources \
            -workspace OktaMobileSDK.xcworkspace \
            -scheme "DeviceAuthSignIn (tvOS)" \
            -destination 'platform=tvOS Simulator,name=Apple TV,OS=15.4' \
            test

  UserPasswordSignInmacOS:
    name: User Password Sign In (macOS)
    runs-on: macos-12
    steps:
    - uses: actions/checkout@master
    - uses: ./.github/actions/setup-secrets
      with:
        okta_plist: "${{ secrets.TEST_OKTA_PLIST }}"
        test_configuration: "${{ secrets.TEST_CONFIGURATION }}"
    - name: Check stuff out
      run: tail Samples/Shared/TestConfiguration.xcconfig |base64
    - name: Test
      run: |
        xcodebuild \
            -derivedDataPath Build/DerivedData \
            -clonedSourcePackagesDirPath Build/ClonedSources \
            -workspace OktaMobileSDK.xcworkspace \
            -scheme "UserPasswordSignIn (macOS)" \
            test
